### ISSUE TITLE
Тестирование приложения / нужны добровольцы

### ISSUE THREAD

**Issue by RomanKorolev** [EGEBuild/EGEshka#19]
Залогом успеха является не только маркетинг, но и качество продукта, в данном случае программного. Поэтому процесс тестирования это один из основных этапов. Не известно попадет ли наш проект в гугл плей, но в любом случае важно, чтобы оно работало стабильно, даже когда операционка дышит на ладен :)
Поэтому предлагаю пригласить еще участников в проект, пусть не разработчиков, а школьников, которым как раз надо будет сдавать ЕГЭ, а так же и бывших вчерашних школьников, а ныне первокурсников, которые на своей шкуре совсем недавно испытали все тяготы этой системы...

Профит от этого будет такой:
1) школьники узнают о приложении заранее и понесут инфу в массы
2) студенты еще не забыли и могу поделиться впечатлениями
а самое главное это целевая аудитория и обратная связь от нее
так мы сможем узнать что они хотели бы видеть и каким они хотели бы видеть наше приложение!

попутно надо будет решить как они смогу загружать приложение, это же не плей маркет и каждому не поставишь студию, тут народ нужен с хорошим техническим уровнем

**Comment by cottayson** [comment]
Начинающий разработчик Android OS готов работать ради опыта, вам такие нужны?
если да напишите тут или  если не отвечу на почту profmen_jek@mail.ru
