### ISSUE TITLE
Дмитрий Вохминов - участники проекта, знакомимся между собой

### ISSUE THREAD

**Issue by Dimich82** [EGEBuild/EGEshka#30]
Приветствую участников проекта.
Меня зовут Дмитрий, родился в Ленинграде в 1982 году, проживаю в общем тоже там.
Только сейчас временно обитаю в Онеге.
Профессиональный программист, обучался в ПГУПСе.
Работал в основном с ораклом, которого весьма люблю и уважаю.
Из яп знаю 
-делфи
-паскаль 
-си
-яву
самостоятельно изучал и применял то, что касается сайтостроения (perl, php, html, javascript, ajax, jquery, mysql). Движок сайта могу сделать с 0.
Поскольку обслуживал сервера оракл на линуксе, имею опыт разработки под линукс.
Так же учил, но сильно забыл
- ассемблер
- пролог
Андроид начал изучать самостоятельно, т.к. считаю это весьма перспективным.
Из интересов личных
1) вождение автомобиля. Вожу с удовольствием, видимо поэтому есть профессиональные права B,C
2) рыбалка. С удовольствием совмещаю 1) и 2). Ловлю в основном нехищников на поплавок и фидер. Хотя и блесну нравиться бросать
3) философия. Изучаю самостоятельно.

Приятно познакомиться,
Дмитрий

**Comment by RomanKorolev** [comment]
информация скопирована в [wiki](https://github.com/EGEBuild/EGEshka/wiki/%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0:-%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9-%D0%92%D0%BE%D1%85%D0%BC%D0%B8%D0%BD%D0%BE%D0%B2)
