### ISSUE TITLE
Подскажите по проекту

### ISSUE THREAD

**Issue by polis89** [EGEBuild/EGEshka#38]
Где смотреть текущие задачи? 
Есть где посмотреть концепцию приложения?

**Comment by RomanKorolev** [comment]
текущие задачи находятся тут https://github.com/EGEBuild/EGEshka/issues собственно говоря "Подскажите по проекту #38" это тоже задача :) народ не очень активно использует этот инструмент для работы и рассматривает его (гит) только как файловое хранилище.
концепция есть в голове у Евгения ( @OsBuilder )
для оперативного решения вопросов используется ВК беседа пиши Евгению https://vk.com/evgenymanko в личку от тебя добавит
